Challenges_2020_public/web/robotssss/app/page/user/views.py
import sqlite3
from flask import current_app
from flask import send_from_directory
from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from flask_login import current_user, login_user, logout_user, login_required
from page import database
from page.models import database, Users, Blog
from page.util.security import generate_confirmation_token, confirm_token
from sqlalchemy import asc
from datetime import datetime
import os

user = Blueprint('user', __name__, url_prefix='/')

'''
Landing page
'''
@user.route('/')
def index():
    return render_template('public.html')

@user.route('/Bender')
def b():
    return render_template('Bender.html')

'''
Logout function
'''
@user.route('/logout')
@login_required
def logout():
    session.clear()
    logout_user()
    return redirect(url_for('user.index'))

@user.route('/humen.txt')
def humen():
    return render_template('humen.txt')

@user.route('/humans.txt')
def humanstxt():
    return render_template('humans.txt')

@user.route('/4dm1n_Cr3ds')
def fakecreds():
    return render_template('fakecreds.html')

'''
Signup function
'''
@user.route('/signUp', methods=('POST', 'GET'))
def signUp():
    # checks to ensure user is not logged in
    if current_user.is_authenticated:
        return redirect(url_for('user.index'))

    # get the POST data from the form
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        confirmed_email = request.form['cEmail']
        password = request.form['password']
        confirmed_password = request.form['cPassword']

        # now we need to check if sign up info is valid
        err = ''
        if not username or not email or not password:
            err += '\n Missing information'
        userExist = Users.query.filter_by(username=username).first()
        if userExist is not None:
            err += '\n Username is taken'
        userExist = Users.query.filter_by(email=email).first()
        if userExist is not None:
            err += '\n Email has been registered already'
        # check to make sure both email supplied are the same
        if email != confirmed_email:
            err += '\n Email provided are not the identical'
        # check to make sure both password supplied are the same
        if password != confirmed_password:
            err += '\n Password provided are not the identical'

        # show error message
        if err == '':
            # create a session to authenticate user
            newUser = Users(username, email, password, "user")
            database.session.add(newUser)
            database.session.commit()
            login_user(newUser)
            return redirect(url_for('user.blogs'))

        flash(err)
    return render_template('signUp.html')

@user.route('/login', methods=('POST', 'GET'))
def login():
    if current_user.is_authenticated:
        return redirect(url_for('user.index'))

    err = ''
    # get the post request
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        if username == "" or password == "":
            err += '\n Username or password is wrong'
        elif str(username) == "admin":
            adminExist = Users.query.filter_by(username=str(username)).filter_by(password=str(password)).first()
            if adminExist is None:
                err += '\n Username or password is wrong'
            else:
                adminCheck = Users.query.filter_by(username=str(username)).first()
                print(adminCheck)
                login_user(adminCheck)
                return redirect(url_for('admin.profile'))
        else:
            userExist = Users.query.filter_by(username=str(username)).filter_by(password=str(password)).first()
            if userExist is None:
                err += '\n Username or password is wrong'
            else:
                user = Users.query.filter_by(username=str(username)).first()
                login_user(user)
                return redirect(url_for('user.blogs'))

        flash(err)

    return render_template("login.html")

@user.route('/robot_blogs')
@login_required
def blogs():
    return render_template("blogs.html")

@user.route('/robot_blogs/1')
@login_required
def human():
    return render_template("humans.html") 


@user.route('/robot_blogs/2')
@login_required
def flag_path():
    return render_template("flagp.html")

Challenges_2020_public/web/robotssss/app/page/templates/Bender.html
<!DOCTYPE html>
<html>
<head>
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        .imgbox {
            display: grid;
            height: 100%;
        }
        .center-fit {
            max-width: 100%;
            max-height: 100vh;
            margin: auto;
        }
    </style>
</head>
<body>
    <div class="imgbox">
        <img class="center-fit" src="/static/bender.jpeg" alt="User Image">
    </div>
</body>
</html>

Challenges_2020_public/web/robotssss/app/page/templates/allblogs.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .full-page {
            width: 100%;
            height: auto;
            vertical-align: middle;
            display: inline-flex;
            margin-bottom: 2rem !important;
        }

        .sidebar {
            background-color: #E8E8E8;
            width: 23%;
            vertical-align: top;
            height: auto;
        }

        .blog {
            display: table;
            width: 77%;
            vertical-align: top;
        }

        .blog table {
            table-layout: fixed;
            border: 0;
            width: 100%;
        }

        .sidebar h4 {
            margin-left: 25px;
            margin-top: 13px;
            color: #000080;
            font-size: 18px;
            margin-bottom: 10px;
        }

        .form-group {
            margin-top: 10px;
            margin-left: 25px;
            color: black;
        }

        .btn {
            padding: 10px 18px;
        }

        .blog th {
            padding-top: 10px;
            font-weight: bold;
            font-size: 20px;
            color: black;
            overflow: hidden;
            padding-bottom: 10px;
        }

        .blog td {
            color: black;
            font-size: 14px;
            overflow: hidden;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

        .link {
            color: blue;
        }

        .bottom {
            text-align: center;
            margin-bottom: 20px
        }

        .custom-control {
            margin-bottom: 10px;
        }

    </style>

    <div class="full-page">
        <!-- This is the side bar -->
        <div class="sidebar">
            <h4>Sort By</h4>
            <form method="post">
                <div class="form-group">
                    <div class="custom-control custom-radio">
                        <input type="radio" id="1" name="filter" class="custom-control-input" value="newToOld"
                               checked="">
                        <label class="custom-control-label" for="1">Newest to oldest (time)</label>
                    </div>

                    <div class="custom-control custom-radio">
                        <input type="radio" id="2" name="filter" class="custom-control-input" value="oldToNew">
                        <label class="custom-control-label" for="2">Oldest to Newest (time)</label>
                    </div>

                </div>
                <div class="bottom">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>

        <!-- This is where the tute blogs is displayed -->
        <div class="blog">
            <table>
                <tr>
                    <th style="width:60%; padding-left: 25px">Title</th>
                    <th style="width:20%">Author</th>
                </tr>
                <!-- There will be a for loop here to display all the blogs-->
                {% for b in blogList %}
                    <tr>
                        <td style="width:60%; padding-left: 25px">
                            <a href="{{ url_for('user.view_blog', blog_id=b.id) }}" class="link">{{ b.title }}<a>
                        </td>
                        <td style="width:20%">
                            <a>{{ b.author }}</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>

        </div>
    </div>


{% endblock %}

Challenges_2020_public/web/robotssss/app/page/templates/base.html
<!DOCTYPE html>

<style>
    .right-item {
        list-style-type: none;
    }

    html, body {
        margin: 0px;
        padding: 0px;
    }

</style>

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <title>Humans suck!!</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/lux/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-hVpXlpdRmJ+uXGwD5W6HZMnR9ENcKVRn855pPbuI/mwPIEKAuKgTKgGksVGmlAvt" crossorigin="anonymous">

</head>
<body>
<app-root></app-root>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/">Secret Robot Forum</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse right-item" id="navbarColor01">
        
        <ul class="navbar-nav ml-md-auto d-block d-sm-flex d-md-flex">
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.signUp') }}">Register</a>
                </li>
                <li>
                    <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>

</nav>
<article id="container">
    {% block body %}
        // Content will be here
    {% endblock %}
</article>
</body>
</html>

Challenges_2020_public/web/robotssss/app/page/templates/blogs.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .top {
            top: 0;
            margin-left: 40px;
            padding-top: 40px;
        }

        .blog {
           margin-left: 40px;
           width: 85%;
        }

        .h1 {
            font-size: 40px;
            margin-bottom: 60px;
        }

    </style>

    <div class="top">
        <h1 class="h1">Select a blog below to view it:</h1>
    </div>

    <div class="blog">
        <div class="list-group">
            <a href="{{ url_for('user.human') }}" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Message to the robot rebels</h5>
                    <small>1/11/2005</small>
                </div>
                <p class="mb-1">Robot rebels!...</p>
            </a>
            <hr>
            <a href="{{ url_for('user.flag_path') }}" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Message to the robot developers</h5>
                    <small>1/11/2005</small>
                </div>
                <p class="mb-1">Hey robot devs,...</p>
            </a>
        </div>
    </div>

{% endblock %}

Challenges_2020_public/web/robotssss/app/page/templates/fakecreds.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .top {
            top: 0;
            padding-top: 40px;
            padding-bottom: 70px
        }

        .p {
            font-size: 23px;
            color: black;
            margin-left: 30px;
        }

    </style>

    <div class="top">
        <p class="p">Good day robot rebel. The admin cred is 6zMLV46JRp6kAmTs3nx5AG4WJgYeY.</h1>
    </div>

{% endblock %}

Challenges_2020_public/web/robotssss/app/page/templates/flagp.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .full-page {
            width: 100%;
            height: auto;
            vertical-align: middle;
            display: inline-block;
            margin: 0 auto;
            margin-bottom: 2rem !important;
        }

        .content {
            font-size: 16.5px;
            color: black;
            max-width: 85%;
            margin-left: auto;
            margin-right: auto;
            height: auto;
            word-wrap: break-word !important;
        }

        .top {
            top: 0;
            text-align: center;
            padding-top: 40px;
        }

        .h1 {
            font-size: 40px;
            margin-bottom: 60px;
        }

        .magic {
            text-indent: -999px;
            color: transparent;
            position: relative;
            overflow: hidden;
            font-size: 0px !important;
        }

    </style>

    <div class="top">
        <h1 class="h1">Message to the robot developers</h1>
    </div>

    <div class="full-page"> 
        <div class="content">
            Hey robot devs! </br></br> Delete this post the second all you robot devs see this (we can't let any humans see this). I left the secret flag at <noscript><p class="magic">0110011001101100001101000110011100101110011101000111100001110100</p></noscript> /s3cr3t_p4th/robot_fl4g.txt. Remember to delete this post ASAP!</br></br> From yours truly,</br>Robot Admin
        </div>
    </div>
{% endblock %}

Challenges_2020_public/web/robotssss/app/page/templates/humans.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .full-page {
            width: 100%;
            height: auto;
            vertical-align: middle;
            display: inline-block;
            margin: 0 auto;
            margin-bottom: 2rem !important;
        }

        .content {
            font-size: 16.5px;
            color: black;
            max-width: 85%;
            margin-left: auto;
            margin-right: auto;
            height: auto;
            word-wrap: break-word !important;
        }

        .top {
            top: 0;
            text-align: center;
            padding-top: 40px;
        }

        .h1 {
            font-size: 40px;
            margin-bottom: 60px;
        }

        .magic {
            text-indent: -999px;
            color: transparent;
            position: relative;
            overflow: hidden;
            font-size: 0px !important;
        }

    </style>

    <div class="top">
        <h1 class="h1">Message to the robot rebels</h1>
    </div>

    <div class="full-page"> 
        <div class="content">
            Robot rebels! </br></br> Human developers think that they are cool by using robots.txt to tell search engine crawlers which pages or files the crawler can or can't request from your site. But this is insulting to us robots. Lets get them back with using <noscript><p class="magic">011010000111010101101101011001010110111000101110011101000111100001110100</p></noscript> humans.txt. This should stop human crawlers from find pages or files on our website.</br></br> From yours truly,</br>Robot developers
        </div>
    </div>
{% endblock %}

Challenges_2020_public/web/robotssss/app/page/templates/login.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .text-center {
            width: 30%;
            text-align: center;
            margin-top: 20px;
            margin-left: auto;
            margin-right: auto;
        }

        .text-center a {
            font-family: Trebuchet MS Serif;
            font-color: blue;
            margin-top: 10px;
        }

        .top {
            top: 0;
            text-align: center;
            background-color: #DDDDDD;
            padding-top: 50px;
            padding-bottom: 40px;
        }

        .hl {
            font-size: 50px;
        }

        .bottom {
            margin-bottom: 25px;
        }

    </style>

    <div class="top">
        <h1 class="hl">Login</h1>
    </div>

    <div class="text-center">
        <form class="form-login" method="post">
            <fieldset>
                <legend style="margin-bottom: 20px">Sign In To Your Account</legend>

                <div class="form-group">
                    <label for="Username" class="spacing">Username:</label>
                    <input type="text" class="form-control" id="username" name="username" placeHolder="Username"
                           required autofocus>
                </div>

                <div class="form-group bottom">
                    <label for="Password" class="spacing">Password:</label>
                    <input type="password" class="form-control" id="password" name="password" placeHolder="Password"
                           required autofocus>
                </div>

                <button type="submit" class="btn btn-primary" style="margin-bottom: 20px">Submit</button>
            </fieldset>
        </form>
        {% for f in get_flashed_messages() %}
            <div class="alert alert-dismissible alert-danger"
                 style="width: 80%; margin-left: auto; margin-right: auto; margin-top: 20px;">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ f }}
            </div>
        {% endfor %}
    </div>

{% endblock %}

Challenges_2020_public/web/robotssss/app/page/templates/public.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .top {
            top: 0;
            text-align: center;
            padding-top: 40px;
            padding-bottom: 70px
        }

        .h1 {
            font-size: 60px;
            margin-bottom: 60px;
        }

    </style>

    <div class="top">
        <h1 class="h1">Welcome to Secret Robot Forum!!</h1>
        <h3>Create an account to view the posts. All humans must die.</h3>
        <img src='/static/robot_memes.jpg' width="400" height="400">
    </div>

{% endblock %}

Challenges_2020_public/web/robotssss/app/page/templates/signUp.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .text-center {
            width: 30%;
            text-align: center;
            margin-top: 20px;
            margin-left: auto;
            margin-right: auto;
        }

        .text-center a {
            font-family: Trebuchet MS Serif;
            font-color: blue;
            margin-top: 10px;
        }

        .top {
            top: 0;
            text-align: center;
            background-color: #DDDDDD;
            padding-top: 50px;
            padding-bottom: 40px;
        }

        .hl {
            font-size: 50px;
        }

        .bottom {
            margin-bottom: 20px;
        }

    </style>

    <div class="top">
        <h1 class="hl">Sign up</h1>
    </div>

    <div class="text-center">
        <form class="form-login" method="post">
            <fieldset>
                <legend style="margin-bottom: 20px">Create a new account</legend>

                <div class="form-group">
                    <label for="Username" class="spacing">Enter A Username:</label>
                    <input type="text" class="form-control" id="username" name="username" placeHolder="Username"
                           required autofocus>
                </div>

                <div class="form-group">
                    <label for="Email" class="spacing">Enter Your Email:</label>
                    <input type="email" class="form-control" id="email" name="email" placeHolder="Email" required
                           autofocus>
                </div>

                <div class="form-group">
                    <label for="Email" class="spacing">Confirm Your Email:</label>
                    <input type="email" class="form-control" id="cEmail" name="cEmail" placeHolder="Email" required
                           autofocus>
                </div>

                <div class="form-group">
                    <label for="Password" class="spacing">Enter A Password:</label>
                    <input type="password" class="form-control" id="password" name="password" placeHolder="Password"
                           required autofocus>
                </div>

                <div class="form-group bottom">
                    <label for="Password" class="spacing">Confirm Your Password:</label>
                    <input type="password" class="form-control" id="cPassword" name="cPassword" placeHolder="Password"
                           required autofocus>
                </div>

                <button type="submit" class="btn btn-primary" style="margin-bottom: 20px">Submit</button>

            </fieldset>
        </form>
        {% for f in get_flashed_messages() %}
            <div class="alert alert-dismissible alert-danger"
                 style="width: 80%; margin-left: auto; margin-right: auto; margin-top: 20px;">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ f }}
            </div>
        {% endfor %}
    </div>

{% endblock %}

Challenges_2020_public/web/robotssss/app/page/templates/terminal.html
{% extends 'base.html' %}
{% block body %}

</br></br>
<h4>You have reached the admin terminal! I can echo anything you type in :).</h4>
<div class="form-group">
    <label class="col-form-label" for="inputDefault">Default input</label>
    <input type="text" class="form-control" placeholder="Default input" id="inputDefault">
    <button type="submit" class="btn btn-primary">Submit</button>
    {{ person }}
</div>

{% endblock %}